name: interactive_print
description: A Dart library to simulate print() without adding a trailing newline for both Native and Web.
version: 1.0.0
homepage: https://github.com/VarunS2002/Dart-interactive_print

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
